### ISSUE TITLE
Translation to loopy is slow

### ISSUE THREAD

**Issue by kaushikcfd** [inducer/pytato#10]
Consider [this small application](https://gist.github.com/kaushikcfd/d5ae4d251ed21cb39cd05e7b1815186f) where we take 500 numpy arrays and 500 pytato arrays and double both of them. The reported timing on my machine is:

```
Numpy took: 0.000705718994140625 secs.
Pytato took: 146.95382499694824 secs.
```

**Comment by kaushikcfd** [comment]
On taking a closer look, it's going from loopy to CL which is the bottleneck. Generating the loopy kernel just takes ~ 2 secs.(out of 146 secs.). So loopy is :potato:.

Although 2 seconds is not ideal, I'm happy to close this.

**Comment by inducer** [comment]
> So, loopy is the true potato.

:rofl: 

Agree we can monitor this and close it for now.
