### ISSUE TITLE
How to implement Array.__bool__?

### ISSUE THREAD

**Issue by inducer** [inducer/pytato#110]
Right now, `pytato.Array` doesn't implement `__bool__`. That's dangerous, as comparisons (such as those used in e.g. convergence checks) always evaluate to something "truthy":
```py
x: Array
if x < 3:
    # always True
```

We should definitely implement `__bool__` in some fashion.

PyOpenCL will transparently transfer Boolean scalars back to the host:
https://github.com/inducer/pyopencl/blob/1527c099bc6baae6773902b3d190fac6ed691328/pyopencl/array.py#L1451-L1458
I don't know if *that's* a good idea because it may lead to inadvertent transfers. (So it's safe functionally, but not that safe in terns of performance.) We could automatically evaluate scalars in boolean contexts, and we face a similar trade-off as pyopencl. What should we do?

**Comment by kaushikcfd** [comment]
> We should definitely implement __bool__ in some fashion.

Tend to disagree here, instead I vote that we `raise` for such invocations. Pytato arrays don't come with an execution contexts. So we have no idea of how to operate on the DAGs + the placeholders values might be missing. Raising at the very least comes with a transparent behavior.

**Comment by kaushikcfd** [comment]
Implemented my proposal in #111.

**Comment by inducer** [comment]
Thanks! You're completely right.

**Comment by kaushikcfd** [comment]
Ok to close this?

**Comment by inducer** [comment]
Yup.
