### ISSUE TITLE
Pooled allocation for temporaries generated in codegen

### ISSUE THREAD

**Issue by kaushikcfd** [inducer/pytato#122]
Consider the following kernel:
```python
knl = lp.make_kernel(
    "{[i]: 0<=i<N}",
    """
    y[i] = 2*x[i]
    """, name="twice")

x = pt.make_placeholder(name="in", dtype=np.float64, shape=1000000)
out = {f"out{i}": call_loopy(knl, {"x": i*x})["y"]
       for i in range(10)}
pt_prg = pt.generate_loopy(out).program
```

The generated code in `pt_prg` will contain 20 temporaries each containing 1 million doubles. Ideally we should have allocated a single temporary of 1 million doubles (assuming we don't inline at the spot.).

We could have such an implementation in pytato via some heuristic pooled allocator. Allocation here means reserving a chunk from the [base_storage](https://documen.tician.de/loopy/ref_kernel.html?highlight=base_storag#loopy.TemporaryVariable.base_storage) of a reserved temporary.

The _160-million byte question_ being: should we do it at the pytato level or is the downstream user expected to do this on their own via some loopy transformations? However, we must take into consideration that the def-use chain is naturally available in pytato's code-generator which would be tougher to extract by the downstream transformers.

I am in favor of having this logic in `pt.CodeGenMapper`.

**Comment by kaushikcfd** [comment]
Note: This would also force the `CodeGenMapper` to add additional dependencies between instructions to avoid access races.

**Comment by inducer** [comment]
I would much rather look at live ranges in the linearized code and insert (pooled, of course) allocations and deallocations of temporaries. Aliasing temporaries and the ensuing tangle of dependencies makes a lot of desirable things very difficult.

**Comment by kaushikcfd** [comment]
> I would much rather look at live ranges in the linearized code and insert (pooled, of course) allocations and deallocations of temporaries. Aliasing temporaries and the ensuing tangle of dependencies makes a lot of desirable things very difficult.

Thanks, agreed that the dependency addition would come too early and would only hurt us. This isn't a pytato problem.

Thanks for the suggestion.
