### ISSUE TITLE
Reshape on empty arrays

### ISSUE THREAD

**Issue by alexfikl** [inducer/pytato#157]
The following case doesn't work in `pytato` but `numpy` happily reshapes it to anything.

```python
x = pt.make_placeholder("x", shape=(0,), dtype=np.float64)
assert pt.reshape(x, (128, 0, 17)).shape == (128, 0, 17)
```

and 

```python
x = pt.make_placeholder("x", shape=(), dtype=np.float64)
pt.reshape(x, (1,))
```
seems to fail at code generation in [here](https://github.com/inducer/pytato/blob/7fcf1a65be0873f9eea991db74713e64685bf9f9/pytato/codegen.py#L411).

xref: inducer/arraycontext#91

**Comment by kaushikcfd** [comment]
Thanksf for the report, please see #158.
