### ISSUE TITLE
pytato.array.normalize_shape_component: Implementation incomplete 

### ISSUE THREAD

**Issue by kaushikcfd** [inducer/pytato#21]
Argument `ns` is not referenced. [cf [here](https://github.com/inducer/pytato/blob/72a499fd30bad5f2c83bf301ef7357b07954e2af/pytato/array.py#L282-L289)]

**Comment by matthiasdiener** [comment]
Can be closed?

**Comment by inducer** [comment]
I think so. Namespaces are no longer a thing. @kaushikcfd?

**Comment by kaushikcfd** [comment]
Yup, this could be closed.
