### ISSUE TITLE
`NamedArray` from `LoopyCall` can't find its shape and dtype

### ISSUE THREAD

**Issue by inducer** [inducer/pytato#212]
cc @matthiasdiener

**Comment by kaushikcfd** [comment]
Sorry, it's not quite clear what this means. `LoopyCallResult` finds it shape and dtype from the `LoopyCall.translation_unit` and `pytato.loopy.call_loopy` raises if those cannot be inferred.

**Comment by inducer** [comment]
Sorry, this made no sense. The graph partitioner silently turned `LoopyCallResult`s into `NamedArray`s, and those `NamedArray`s then were very confused about how to retrieve their shapes. My bad. Nothing to see here. Sorry again for the noise.
