### ISSUE TITLE
[RFC] Adding metadata to avoid modulo in indirect addressing

### ISSUE THREAD

**Issue by kaushikcfd** [inducer/pytato#221]
## Problem
For the advanced indexing `a[b]` in the following pytato code,
```python
a = pt.make_placeholder("a", 10, np.float64)
b = pt.make_placeholder("b", 10, np.int32)
print(pt.generate_loopy(a[b]).program)
```

we generate the following code:
```python
---------------------------------------------------------------------------
INSTRUCTIONS:
for _pt_out_dim0
  _pt_out[_pt_out_dim0] = a[b[_pt_out_dim0] % 10]  {id=_pt_out_store}
end _pt_out_dim0
---------------------------------------------------------------------------
```
This is inefficient and in certain cases is ~saturating the modulo unit~ the temporaries for the modulo are occupying significant register space on the device costing us 50% of the runtime costs for computing the RHS in https://github.com/illinois-ceesd/drivers_y1-nozzle.

## Proposed Solution
A tag `AssumeNonNegative()` that would inform the code generator to assume all entries in the array to be positive, which can then be used to generate code without the modulo op. The original code would now look as:

```python
a = pt.make_placeholder("a", 10, np.float64)
b = pt.make_placeholder("b", 10, np.int32).tagged(pt.tags.AssumeNonNegative())
print(pt.generate_loopy(a[b]).program)
```
and should generate code without any modulos in it.

**Comment by inducer** [comment]
Two quibbles:
- IMO, this should be an axis tag, as the decision is a per-axis one.
- The name isn't descriptive enough yet IMO. `NonNegativelyIndexedAxis` maybe?

> costing us 50% of the runtime costs

Yikes! Good thing you looked into this.

**Comment by kaushikcfd** [comment]
I'm not sure making this an axis serves a great purpose as we need the information about the entries of the entire (not per-axis) volume of indirection map array. As proposed earlier, I think tagging the indirection map array with `AssumeNonNegative` (to notify that all the entries of the indirection map are non-negative) should be enough for the code-generator to skip the modulo as demonstrated here: https://github.com/inducer/pytato/pull/222/files#diff-58500e476c53854fbefa3329b2fa5cf84d63193cbf11a89da361acce596f83faR1384-R1410.

**Comment by inducer** [comment]
Hmm. I did misunderstand you in a pretty basic way: I though the tag was going to go on the subscript `IndexLambda`, not the array of indices. Now that that misunderstanding is resolved, I agree that this is reasonable, specifically I agree that tagging the array of indices makes sense, as the tag on the `IndexLambda` has the potential for ambiguity without additional assumptions. Sorry for the noise!
