### ISSUE TITLE
`CachedMapper.__call__` should override types borrowed from `Mapper.__call__`

### ISSUE THREAD

**Issue by kaushikcfd** [inducer/pytato#236]

**Comment by inducer** [comment]
What do you mean by "borrowed types"?

**Comment by kaushikcfd** [comment]
Since `CachedMapper` is derived from `Mapper`. `CachedMapper.__call__` has the same type as `Mapper.__call__`, but `CachedMapper.__call__` can be further specialized based on `CachedMapperT`.
