### ISSUE TITLE
Docs does not show the types

### ISSUE THREAD

**Issue by kaushikcfd** [inducer/pytato#244]
![image](https://user-images.githubusercontent.com/15399010/149071940-f3469576-6e47-437d-b11b-744a1a9827f8.png)

**Comment by matthiasdiener** [comment]
I think they need to be mentioned explicitly with `:params ...:` to be shown.

![image](https://user-images.githubusercontent.com/1772435/149187504-e2c616c7-f0bf-49be-8e2b-fa277475ce1b.png)
