### ISSUE TITLE
[Enhancement] CopyMapper should allow passing `*args`, `**kwargs`.

### ISSUE THREAD

**Issue by kaushikcfd** [inducer/pytato#276]

**Comment by inducer** [comment]
These do increase cost per call frame (which I think is the main cost driver for mappers), so I'm a little wary of adding them (or at least `**kwargs`, which I think is fairly expensive. I don't have benchmark numbers though, so this concern could be easily resolved via some measurements.

**Comment by kaushikcfd** [comment]
Thanks.

> These do increase cost per call frame 

Yep, agree. These would also increase the `cache_key` computation cost. I have included a separate mapper "CopyMapperWithExtraArgs" in #277.

**Comment by inducer** [comment]
Yep, nice. Having it as a separate mapper type is a good idea. It's a bit of code duplication, but I think that's an OK price to pay.
