### ISSUE TITLE
What if a `DistributedRecv` disappears from a DAG because it's unused?

### ISSUE THREAD

**Issue by inducer** [inducer/pytato#279]

**Comment by kaushikcfd** [comment]
Free dead code elimination. :)

**Comment by kaushikcfd** [comment]
> Free dead code elimination. :)

Possibly at the cost of deadlocks.

**Comment by inducer** [comment]
Yep. Not a super-pressing concern at this point. I'm tempted to just document the issue and move on. What do you think?

**Comment by kaushikcfd** [comment]
Yep, it's almost impossible to even catch those. Probably just documenting is the best we can do?
