### ISSUE TITLE
Look for uses of `pyrsistent.Map` where no updates occur, replace with `immutables.Map`

### ISSUE THREAD

**Issue by inducer** [inducer/pytato#303]
x-ref: https://gist.github.com/1st1/292e3f0bbe43bd65ff3256f80aa2637d?permalink_comment_id=2399355
x-ref: https://github.com/inducer/pytato/pull/277#discussion_r837867347

cc @kaushikcfd

**Comment by kaushikcfd** [comment]
Closed by #383.
