### ISSUE TITLE
Post-review of transition to `attrs`

### ISSUE THREAD

**Issue by inducer** [inducer/pytato#370]
After merging #365, I noticed a few things I wish I'd flagged, see https://github.com/inducer/pytato/pull/365#pullrequestreview-1147957251. They're not a huge deal, but I think we should address them to avoid setting traps for our future selves.

**Comment by kaushikcfd** [comment]
From https://github.com/inducer/pytato/pull/371#discussion_r999778468, automaticall populate `_fields`.

**Comment by matthiasdiener** [comment]
Out of curiosity, should we now consider moving back to `dataclasses` (which would imply Python 3.10+)?

**Comment by inducer** [comment]
In general, I'm in favor of that. Good reasons to go back:

- uniformity? Everywhere else in the stack uses dataclasses.
- https://docs.python.org/3/library/typing.html#typing.dataclass_transform would allow us to define a single class decorator for array-likes, vs. the inconsistent mess that we have currently.

Obstacles:
- We're using `cache_hash=True` in attrs, for which dataclasses has no equivalent. We would need to generate our own code for `__hash__`. Could be worse, I think.
