### ISSUE TITLE
CachedWalkMapper may be visiting repeated expressions more than once

### ISSUE THREAD

**Issue by ecisneros8** [inducer/pytato#454]
Discussed today in Pyro meeting with @inducer.

Say we want to count, excluding redundancies, the number of log(x) in 

```
def some_fun(x):
    return actx.np.stack([
        1 + actx.np.log(x),
        1 + 2 * actx.np.log(x),
        1 + 3 * actx.np.log(x),
    ])
```

where `actx = PytatoJAXArrayContext()` and `x` a `:pytato:array.Placeholder`. With a `CachedWalkerMapper` such as

```
class LogCounter(pt.transform.CachedWalkMapper):
    def __init__(self):
        self.num_log = 0
        super().__init__()

    def map_index_lambda(self, expr):
        from pytato.raising import index_lambda_to_high_level_op
        from pytato.raising import C99CallOp
        
        hi_lev_op = index_lambda_to_high_level_op(expr)        

        if isinstance(hi_lev_op, C99CallOp):   
            
            if hi_lev_op.function == 'log':
                self.num_log += 1
        
        super().map_index_lambda(expr) 
```

the count `LogCounter()(some_fun(x)).num_log = 3`, though the anticipated answer would have been 1.  What I think is happening is that each`actx.np.log(x)` in `some_fun` get different cache key `id`, hence counted repeatedly.

**Comment by kaushikcfd** [comment]
This seems to be using an older pytato? Because newer pytato requires the mapper implementation to provide the cache key (https://github.com/inducer/pytato/blob/main/pytato/transform/__init__.py#L1155). I.e. this cache key determines which nodes in the graph are different.


In an older pytato version, we had used `id(x)` as the cache key and I see three different instances of `pt.log(x)` in the provided DAG.

**Comment by ecisneros8** [comment]
Hi @kaushikcfd

Yes, you are correct. This is an older version. The specific CachedWalkMapper being used can be found [here](https://github.com/inducer/pytato/blob/28c0e18605b5ffc9c120acb4f132aef80d2fee10/pytato/transform/__init__.py#L943)

**Comment by ecisneros8** [comment]
I'll go work with `main` and implement the corresponding `get_key_cache()`. Any hints will be much appreciated!

**Comment by kaushikcfd** [comment]
Using `expr = CopyMapper()(expr)` and then using the cache key as `id(x)` is another way to get the desired behavior you are looking for.

**Comment by ecisneros8** [comment]
Thank you @kaushikcfd !

**Comment by matthiasdiener** [comment]
Would 

```python
def get_cache_key(self, expr):
    return expr
```

be a workaround?



Full code:

```python
import arraycontext
actx = arraycontext.PytatoJAXArrayContext()
import pytato as pt
import numpy as np

x = pt.make_placeholder(name="x", shape=(2,2), dtype=np.float64)

def some_fun(x):
    return actx.np.stack([
        1 + actx.np.log(x),
        1 + 2 * actx.np.log(x),
        1 + 3 * actx.np.log(x),
    ])


class LogCounter(pt.transform.CachedWalkMapper):
    def __init__(self):
        super().__init__()
        self.num_log = 0

    def get_cache_key(self, expr):
        return expr

    def map_index_lambda(self, expr):
        from pytato.raising import index_lambda_to_high_level_op
        from pytato.raising import C99CallOp

        hi_lev_op = index_lambda_to_high_level_op(expr)

        if isinstance(hi_lev_op, C99CallOp):

            if hi_lev_op.function == 'log':
                self.num_log += 1

        super().map_index_lambda(expr)

l = LogCounter()
l(some_fun(x))

print(l.num_log)
print(pt.analysis.get_num_nodes(some_fun(x)))
```

**Comment by kaushikcfd** [comment]
The only issue in `get_cache_key` as identity function is that the comparisons might get expensive depending on the graph structure.

**Comment by matthiasdiener** [comment]
> The only issue in `get_cache_key` as identity function is that the comparisons might get expensive depending on the graph structure.

Would `hash(expr)` be a better key? The hash itself is already cached in `attrs`.

**Comment by ecisneros8** [comment]
For completeness

```
def get_cache_key(self, expr):
        expr = pt.transform.CopyMapper()(expr)
        return id(expr)
```

works just as well as

```
def get_cache_key(self, expr):
        return expr
```

and 

```
def get_cache_key(self, expr):
        return hash(expr)
```
