### ISSUE TITLE
Proposal: Default return_dict to True in generate_loopy

### ISSUE THREAD

**Issue by inducer** [inducer/pytato#47]
If `options` are not provided, put in ones that set `return_dict`? (IMO, non-`return_dict` hardly ever makes sense for pytato.)

@kaushikcfd Thoughts?

**Comment by inducer** [comment]
Or: how about defaulting to that if result is a `DictOfNamedArray`s?

**Comment by kaushikcfd** [comment]
Yep, agree with both together i.e.: `return_dict = isinstance(outputs, DictOfNamedArrays)`
