### ISSUE TITLE
Mappers should now traverse shapes

### ISSUE THREAD

**Issue by inducer** [inducer/pytato#68]
Those can now contain further arrays, after all.

cc @kaushikcfd

**Comment by kaushikcfd** [comment]
We did that, see https://github.com/inducer/pytato/blob/6f92045f5a4fc1d31660be0731da9ef6106474c2/pytato/transform.py#L106-L108.

**Comment by inducer** [comment]
D'oh! Thanks for pointing that out, and sorry about the false alarm.

**Comment by kaushikcfd** [comment]
No worries! :)
