### ISSUE TITLE
DependencyMapper semantics

### ISSUE THREAD

**Issue by inducer** [inducer/pytato#8]
@kaushikcfd This hadn't occurred to me when I reviewed it, but the semantics for the `DependencyMapper` are actually not clearly defined. The current one provides all subexpressions that go into the argument. Some other possibilities:

- All named arrays (i.e. things known by the `Namespace`)
- All scalar/integer parameters

**Comment by kaushikcfd** [comment]
1. Took pymbolic's approach i.e. dependencies of array expressions are array expressions.

2. The suggested variants (i.e. named arrays, scalar/int params) can be derived from what's currently returned. We could add helpers for them too if the pattern starts recurring within the codebase. For ex. to get the kernel argument names one can write:
```python
deps = set().union(*list(get_dependencies(source_dict).values()))
dep_names = (set([dep.name
                  for dep in deps
                  if isinstance(dep, (Placeholder, DataWrapper))])
             | get_scalar_expr_deps([dep.shape for dep in deps]))
```

**Comment by inducer** [comment]
The main difference there is that your variants construct much larger (size of the whole expression tree) intermediate data structures. But sure, it can wait, particularly since `DependencyMapper` is more internal-facing.
